# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4517ea1fa5f579c39b6e0c326f4369c3b00a483a0b78bfc7298473e571ccdd12c8775dc7c3d47459a0abe840897c0097227541c0dde4f1a5ef7e40afa5e7a920

test:
  secret_key_base: 08ffa316d7d1ac3e83ebaf684a44747270c871b7b97a93ed9c1ef227d11e008d6fb9ce01889b47f9f791359a5810fafd01940d6414827d34275fa21667585b7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
